### ISSUE TITLE
Feature Request: Colored Icons

### ISSUE THREAD

**Issue by jbgy** [refact0r/monkeytype-themes#3]
Can you do make a custom snippet where it colors the icons? like in the nord, dracula theme but so it can be used with other themes

**Comment by refact0r** [comment]
I don't actively maintain this repository anymore.
But if you want to color the icons, you would do something like this:

```css
.textButton.view-start {
    color: blue;
}
.textButton.view-leaderboards {
    color: blue;
}
.textButton.view-about {
    color: blue;
}
.textButton.view-settings {
    color: blue;
}
.textButton.view-account {
    color: blue;
}
.text.showAlerts {
    color: blue;
}
.text.signInOut {
    color: blue;
}
```
